# Generated by Django 3.2.15 on 2022-09-30 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_entity_rbac.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('members', models.ManyToManyField(related_name='pd_roletestapp_parentmodel', through='roletestapp.Membership', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(django_entity_rbac.models.AccessControlledModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='membership',
            name='parentmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='roletestapp.parentmodel'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_roletestapp_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=15)),
                ('visibility', models.IntegerField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roletestapp.parentmodel')),
            ],
            bases=(django_entity_rbac.models.AccessControlledModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('parentmodel', 'user'), name='memb_uniq'),
        ),
    ]
